apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kraft-kafka-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kadirsahan/kraft-kafka-server.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: kraft-kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
